export enum CardKindEnum {
    ASSASSINAT = "ASSASSINAT",
    CHANGEFORME = "CHANGEFORME",
    ESPION = "ESPION",
    DECRET_ROYAL = "DECRET_ROYAL",
    ARCHER = "ARCHER",
    EMBUSCADE = "EMBUSCADE",
    SOLDAT = "SOLDAT",
    COMPLOT = "COMPLOT",
    SEIGNEUR = "SEIGNEUR",
    HERITIER = "HERITIER"
}
